export const GOOGLE_TTS_LANGUAGE_MAP: Record<string, { languageCode: string; voiceName: string }> = {
  en: { languageCode: 'en-IN', voiceName: 'en-IN-Wavenet-A' },
  bn: { languageCode: 'bn-IN', voiceName: 'bn-IN-Wavenet-A' },
  hi: { languageCode: 'hi-IN', voiceName: 'hi-IN-Wavenet-A' },
  ta: { languageCode: 'ta-IN', voiceName: 'ta-IN-Wavenet-A' },
  as: { languageCode: 'as-IN', voiceName: 'as-IN-Standard-A' },
  gu: { languageCode: 'gu-IN', voiceName: 'gu-IN-Wavenet-A' },
  kn: { languageCode: 'kn-IN', voiceName: 'kn-IN-Wavenet-A' },
  ml: { languageCode: 'ml-IN', voiceName: 'ml-IN-Wavenet-A' },
  mr: { languageCode: 'mr-IN', voiceName: 'mr-IN-Wavenet-A' },
  or: { languageCode: 'or-IN', voiceName: 'or-IN-Standard-A' },
  pa: { languageCode: 'pa-IN', voiceName: 'pa-IN-Standard-A' },
  te: { languageCode: 'te-IN', voiceName: 'te-IN-Wavenet-A' },
  ur: { languageCode: 'ur-IN', voiceName: 'ur-IN-Wavenet-A' },
  sd: { languageCode: 'sd-IN', voiceName: 'sd-IN-Standard-A' },
  ne: { languageCode: 'ne-NP', voiceName: 'ne-NP-Standard-A' },
  kok: { languageCode: 'kok-IN', voiceName: 'kok-IN-Standard-A' },
  mai: { languageCode: 'mai-IN', voiceName: 'mai-IN-Standard-A' },
  trp: { languageCode: 'trp-IN', voiceName: 'trp-IN-Standard-A' },
  grt: { languageCode: 'grt-IN', voiceName: 'grt-IN-Standard-A' },
  mni: { languageCode: 'mni-IN', voiceName: 'mni-IN-Standard-A' },
  lus: { languageCode: 'lus-IN', voiceName: 'lus-IN-Standard-A' },
  sat: { languageCode: 'sat-IN', voiceName: 'sat-IN-Standard-A' },
  doi: { languageCode: 'doi-IN', voiceName: 'doi-IN-Standard-A' },
};